---
editor_options: 
  chunk_output_type: console
---

```{r setup09, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = "")
options(scipen=999)
library(tidyverse)
theme_set(theme_bw())
```

# Темы для финального проекта

1. Автоматическое извлечение саркастических высказываний из текстов на русском языке

2. Сочетаемость глаголов мыслительной деятельности в русском языке

3. Автоматическое определение тематики новостного заголовка в текстах региональных СМИ

4. Глаголы движения в английском языке

5. Сочетаемость выражения *с гаком*

6. Автоматическое извлечение ироничных высказываний из текстов на английском языке

7. Частица *-то* в севернорусских говорах

8. Конструкции со значением близости к результату в русском языке

9. Аномальное управление в предложно-падежных сочетаниях: сопоставительный корпусный анализ носителей с разными доминантными языками 

10. Автоматическое извлечение метафорических высказываний из текстов на русском языке

11. *Как раз* в современном русском языке

12. Конструкции с предлогом *на* в западнорусских говорах