
--- 
title: "Получение и обработка корпусных данных для лингвистических исследований"
author: "Е. А. Заливина"
bibliography: bibliography.bib
editor_options:
  chunk_output_type: console
link-citations: yes
documentclass: book
site: bookdown::bookdown_site
biblio-style: apalike
---

# О курсе

Материалы для курса Получение и обработка корпусных данных для лингвистических исследований.

## Пререквизиты
* владение Excel на базовом уровне (суммирование, округление, сортировка)
* владение Python на базовом уровне (умение работать с разными типами данных: списки, словари и т.д.) 

## Цель курса
Студент может собрать и обработать релевантные данные для своего исследования

## Планируемые образовательные результаты
1. Студент может перечислить виды корпусов
2. Студент может привести пример исследования, данные для которого собирались бы в заданном корпусе
3. Студент может составить релевантный для исследования запрос для поиска по корпусу
4. Студент может разработать поэтапный план поиска и подготовки данных для заданного исследования
5. Студент может применять табличный редактор для сортировки, фильтрации и конкатенации данных
6. Студент может перечислить библиотеки Python, которые можно применить для сбора данных и дальнейшей работы с ними
7. Студент может объяснить принцип очистки данных (какие примеры были убраны и почему)

## Оценка

Всего четыре домашних задания и финальный проект. 

0.1 * дз1 + 0.2 * дз2 + 0.2 * дз3 + 0.1 * дз4 + 0.4 * финальный проект

## Подробнее о курсе
[Здесь](https://docs.google.com/document/d/1Gs3j5UmIMGKJIrXjuTNr974cm7cs3RiiqIHDZ4r4iAA/edit?usp=sharing)
